/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String name = "";

    public String getGreeting() {
        return "Hello World! First gradle project by Subodh";
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }
    
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
